### ISSUE TITLE
mod fails to load—NoSuchMethodError

### ISSUE THREAD

**Issue by robofunc** [MinecraftModDevelopment/Extra-Golems#136]
Crash report:

---- Minecraft Crash Report ----
// There are four lights!

Time: 2024-08-17 10:43:11
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at TRANSFORMER/forge@50.1.0/net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:48) ~[forge-1.20.6-50.1.0-universal.jar:?] {re:classloading}
	at TRANSFORMER/forge@50.1.0/net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:119) ~[forge-1.20.6-50.1.0-universal.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.client.Minecraft.lambda$new$6(Minecraft.java:621) ~[forge-1.20.6-50.1.0-client.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.Util.ifElse(Util.java:475) ~[forge-1.20.6-50.1.0-client.jar:?] {re:classloading}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.client.Minecraft.lambda$new$7(Minecraft.java:614) ~[forge-1.20.6-50.1.0-client.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at TRANSFORMER/forge@50.1.0/net.minecraftforge.client.loading.ForgeLoadingOverlay.render(ForgeLoadingOverlay.java:146) ~[forge-1.20.6-50.1.0-universal.jar:?] {re:classloading}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:886) ~[forge-1.20.6-50.1.0-client.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.client.Minecraft.runTick(Minecraft.java:1238) ~[forge-1.20.6-50.1.0-client.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.client.Minecraft.run(Minecraft.java:800) ~[forge-1.20.6-50.1.0-client.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.client.main.Main.main(Main.java:242) ~[forge-1.20.6-50.1.0-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.6-50.1.0/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:91) ~[fmlloader-1.20.6-50.1.0.jar!/:?] {}
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.6-50.1.0/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:75) ~[fmlloader-1.20.6-50.1.0.jar!/:?] {}
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:77) [modlauncher-10.2.1.jar!/:?] {}
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:97) [modlauncher-10.2.1.jar!/:?] {}
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.Launcher.run(Launcher.java:116) [modlauncher-10.2.1.jar!/:?] {}
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.Launcher.main(Launcher.java:75) [modlauncher-10.2.1.jar!/:?] {}
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.BootstrapEntry.main(BootstrapEntry.java:17) [modlauncher-10.2.1.jar!/:?] {}
	at net.minecraftforge.bootstrap@2.1.3/net.minecraftforge.bootstrap.Bootstrap.moduleMain(Bootstrap.java:188) [bootstrap-2.1.3.jar!/:?] {}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at net.minecraftforge.bootstrap.Bootstrap.bootstrapMain(Bootstrap.java:133) [bootstrap-2.1.3.jar:2.1.3] {}
	at net.minecraftforge.bootstrap.Bootstrap.start(Bootstrap.java:53) [bootstrap-2.1.3.jar:2.1.3] {}
	at net.minecraftforge.bootstrap.ForgeBootstrap.main(ForgeBootstrap.java:19) [bootstrap-2.1.3.jar:2.1.3] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mod: 
	Extra Golems (golems), Version: 20.1.0.2
		Issue tracker URL: https://github.com/MinecraftModDevelopmentMods/Extra-Golems/issues
		at TRANSFORMER/golems@20.1.0.2/com.mcmoddev.golems.network.EGNetwork.<clinit>(EGNetwork.java:14)
Stacktrace:
	at TRANSFORMER/golems@20.1.0.2/com.mcmoddev.golems.network.EGNetwork.<clinit>(EGNetwork.java:14) ~[?:?] {re:classloading}
-- MOD golems --
Details:
	Mod File: /Users/mpzvk/Library/Application Support/minecraft/mods/extragolems-20.1.0.2.jar
	Failure message: Extra Golems (golems) has failed to load correctly
		java.lang.NoSuchMethodError: 'net.minecraftforge.network.simple.SimpleChannel net.minecraftforge.network.NetworkRegistry.newSimpleChannel(net.minecraft.resources.ResourceLocation, java.util.function.Supplier, java.util.function.Predicate, java.util.function.Predicate)'
	Mod Version: 20.1.0.2
	Mod Issue URL: https://github.com/MinecraftModDevelopmentMods/Extra-Golems/issues
	Exception message: java.lang.NoSuchMethodError: 'net.minecraftforge.network.simple.SimpleChannel net.minecraftforge.network.NetworkRegistry.newSimpleChannel(net.minecraft.resources.ResourceLocation, java.util.function.Supplier, java.util.function.Predicate, java.util.function.Predicate)'
Stacktrace:
	at TRANSFORMER/golems@20.1.0.2/com.mcmoddev.golems.network.EGNetwork.<clinit>(EGNetwork.java:14) ~[extragolems-20.1.0.2.jar!/:20.1.0.2] {re:classloading}
	at TRANSFORMER/golems@20.1.0.2/com.mcmoddev.golems.ExtraGolems.<init>(ExtraGolems.java:48) ~[extragolems-20.1.0.2.jar!/:20.1.0.2] {re:classloading}
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?] {}
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?] {}
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?] {}
	at LAYER PLUGIN/net.minecraftforge.javafmlmod@1.20.6-50.1.0/net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:66) ~[javafmllanguage-1.20.6-50.1.0.jar!/:50.1.0] {}
	at LAYER PLUGIN/net.minecraftforge.fmlcore@1.20.6-50.1.0/net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$5(ModContainer.java:125) ~[fmlcore-1.20.6-50.1.0.jar!/:1.0] {}
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.20.6
	Minecraft Version ID: 1.20.6
	Operating System: Mac OS X (x86_64) version 12.7.6
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 345061816 bytes (329 MiB) / 671088640 bytes (640 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 61 Stepping 4
	Microarchitecture: Broadwell (Client)
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel Iris Graphics 6100
	Graphics card #0 vendor: Intel
	Graphics card #0 VRAM (MB): 1536.00
	Graphics card #0 deviceId: 0x162b
	Graphics card #0 versionInfo: Revision ID: 0x0009
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.87
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.87
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 17408.00
	Virtual memory used (MB): 9863.40
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 192.50
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 10.2.1
	ModLauncher launch target: forge_client
	ModLauncher naming: mcp
	ModLauncher services: 
		/ slf4jfixer PLUGINSERVICE 
		/ runtimedistcleaner PLUGINSERVICE 
		/ runtime_enum_extender PLUGINSERVICE 
		/ object_holder_definalize PLUGINSERVICE 
		/ capability_token_subclass PLUGINSERVICE 
		/ accesstransformer PLUGINSERVICE 
		/ eventbus PLUGINSERVICE 
		/ mixin PLUGINSERVICE 
		/ fml TRANSFORMATIONSERVICE 
		/ mixin TRANSFORMATIONSERVICE 
	FML Language Providers: 
		lowcodefml@50
		minecraft@1.0
		javafml@50.1.0
	Mod List: 
		forge-1.20.6-50.1.0-client.jar                    |Minecraft                     |minecraft                     |1.20.6              |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.20.6-50.1.0-universal.jar                 |Forge                         |forge                         |50.1.0              |COMMON_SET|Manifest: NOSIGNATURE
		extragolems-20.1.0.2.jar                          |Extra Golems                  |golems                        |20.1.0.2            |ERROR     |Manifest: NOSIGNATURE
	Crash Report UUID: 2fbc0c71-19b2-4fea-a176-5b1adf021998
	FML: 0.0
	Forge: net.minecraftforge:50.1.0

**Comment by skyjay1** [comment]
Extra Golems 20.1.0.2 is for Forge 1.20.1. You are using 1.20.6
