### ISSUE TITLE
[COL][SERVER] Crash on server load

### ISSUE THREAD

**Issue by drakray** [MinecraftModDevelopment/Extra-Golems#15]
ExtraGolem 7.0.1
https://pastebin.com/uX8jBHSR
```
Description: Exception in server tick loop
 
java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen
    at com.golems.proxies.CommonProxy.registerItems(CommonProxy.java:156)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_107_CommonProxy_registerItems_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:807)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by skyjay1** [comment]
Fixed in latest release 7.1.0
Thank you for letting us know!
