### ISSUE TITLE
NPE caused by com.golems.entity.GolemBase.func_70636_d(GolemBase.java:200)

### ISSUE THREAD

**Issue by Tomas-Kraus** [MinecraftModDevelopment/Extra-Golems#37]
My 1.12.2 server crashed because of this exception:
```
[06:49:49] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
        at net.minecraft.pathfinding.WalkNodeProcessor.func_186332_a(WalkNodeProcessor.java:192) ~[beo.class:?]
        at net.minecraft.pathfinding.WalkNodeProcessor.func_186332_a(WalkNodeProcessor.java:219) ~[beo.class:?]
        at net.minecraft.pathfinding.WalkNodeProcessor.func_186320_a(WalkNodeProcessor.java:113) ~[beo.class:?]
        at net.minecraft.pathfinding.PathFinder.func_186335_a(SourceFile:82) ~[bem.class:?]
        at net.minecraft.pathfinding.PathFinder.func_186334_a(SourceFile:40) ~[bem.class:?]
        at net.minecraft.pathfinding.PathFinder.func_186336_a(SourceFile:30) ~[bem.class:?]
        at net.minecraft.pathfinding.PathNavigate.func_179680_a(SourceFile:114) ~[ze.class:?]
        at net.minecraft.pathfinding.PathNavigateGround.func_179680_a(SourceFile:51) ~[zd.class:?]
        at net.minecraft.pathfinding.PathNavigate.func_75488_a(SourceFile:93) ~[ze.class:?]
        at net.minecraft.pathfinding.PathNavigate.func_75492_a(SourceFile:143) ~[ze.class:?]
        at net.minecraft.entity.ai.EntityAIWander.func_75249_e(SourceFile:65) ~[yc.class:?]
        at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:102) ~[xf.class:?]
        at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763) ~[vq.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2352) ~[vp.class:?]
        at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) ~[vq.class:?]
        at com.golems.entity.GolemBase.func_70636_d(GolemBase.java:200) ~[GolemBase.class:?]
        at com.golems.entity.EntityRedstoneGolem.func_70636_d(EntityRedstoneGolem.java:82) ~[EntityRedstoneGolem.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172) ~[vp.class:?]
        at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) ~[vq.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:1993) ~[amu.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) ~[oo.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:1955) ~[amu.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1759) ~[amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
```

**Comment by Tomas-Kraus** [comment]
It was Extra Golems 7.0.0-beta1.4.

**Comment by skyjay1** [comment]
Why are you not using the latest version of Extra Golems? Beta versions are always buggy. Switch to [7.1.5](https://www.curseforge.com/minecraft/mc-mods/extra-golems/files/2722605).
