### ISSUE TITLE
I can't create the golems and the guide book crashes my game.

### ISSUE THREAD

**Issue by pro14812345** [MinecraftModDevelopment/Extra-Golems#89]

**Comment by dshadowwolf** [comment]
The Forge log-file, at a minimum, if not the log file and the crash report, would be helpful in knowing what is going on and figuring out how to fix it.

Programmers aren't some sort of psychic superhuman - we need information so that we can tell what is going on to cause the crashes. Please provide as much information as possible - including the log-files mentioned - so that the issue can be found and the crash fixed.

**Comment by pro14812345** [comment]
I'm using a minecraft java launcher called pojav launcher so maybe it have some differents.

---- Minecraft Crash Report ----
// Why did you do that?

Time: 10/19/21 8:21 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.mcmoddev.golems.golem_stats.GolemContainer.getAllBlocks(GolemContainer.java:359) ~[golems:16.5.2] {re:classloading}
	at com.mcmoddev.golems.golem_stats.GolemContainer.getAllBlocks(GolemContainer.java:270) ~[golems:16.5.2] {re:classloading}
	at com.mcmoddev.golems.screen.GolemBookEntry.<init>(GolemBookEntry.java:45) ~[golems:16.5.2] {re:classloading}
	at com.mcmoddev.golems.screen.GolemBookScreen.initGolemBookEntries(GolemBookScreen.java:147) ~[golems:16.5.2] {re:classloading}
	at com.mcmoddev.golems.screen.GolemBookScreen.<init>(GolemBookScreen.java:131) ~[golems:16.5.2] {re:classloading}
	at com.mcmoddev.golems.screen.EGScreenLoader.loadBookGui(EGScreenLoader.java:19) ~[golems:16.5.2] {re:classloading}
	at com.mcmoddev.golems.item.GuideBookItem.func_77659_a(GuideBookItem.java:24) ~[golems:16.5.2] {re:classloading}
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217) ~[?:?] {re:classloading,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack}
	at net.minecraft.client.multiplayer.PlayerController.func_187101_a(PlayerController.java:328) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1389) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1645) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1460) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5-forge-36.2.8.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0-internal] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0-internal] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0-internal] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0-internal] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.8.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mcmoddev.golems.golem_stats.GolemContainer.getAllBlocks(GolemContainer.java:359) ~[golems:16.5.2] {re:classloading}
	at com.mcmoddev.golems.golem_stats.GolemContainer.getAllBlocks(GolemContainer.java:270) ~[golems:16.5.2] {re:classloading}
	at com.mcmoddev.golems.screen.GolemBookEntry.<init>(GolemBookEntry.java:45) ~[golems:16.5.2] {re:classloading}
	at com.mcmoddev.golems.screen.GolemBookScreen.initGolemBookEntries(GolemBookScreen.java:147) ~[golems:16.5.2] {re:classloading}
	at com.mcmoddev.golems.screen.GolemBookScreen.<init>(GolemBookScreen.java:131) ~[golems:16.5.2] {re:classloading}
	at com.mcmoddev.golems.screen.EGScreenLoader.loadBookGui(EGScreenLoader.java:19) ~[golems:16.5.2] {re:classloading}
	at com.mcmoddev.golems.item.GuideBookItem.func_77659_a(GuideBookItem.java:24) ~[golems:16.5.2] {re:classloading}
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217) ~[?:?] {re:classloading,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack}
	at net.minecraft.client.multiplayer.PlayerController.func_187101_a(PlayerController.java:328) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1389) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1645) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['x_Fusion_snipezz'/1, l='ClientLevel', x=7.20, y=4.00, z=9.87]]
	Chunk stats: Client Chunk Cache: 841, 529
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,4,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1652 game time, 1652 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5-forge-36.2.8.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0-internal] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0-internal] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0-internal] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0-internal] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.8.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (aarch64) version Android-11
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 610603952 bytes (582 MB) / 1043857408 bytes (995 MB) up to 1043857408 bytes (995 MB)
	CPUs: 8
	JVM Flags: 3 total; -Xms1028M -Xmx1028M -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/ResConfHack.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.8.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.8.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.8.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.8.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.8.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.8
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.8-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.8-universal.jar                 |Forge                         |forge                         |36.2.8              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		extragolems-16.5.2.jar                            |Extra Golems                  |golems                        |16.5.2              |DONE      |Manifest: NOSIGNATURE
		mobbattle-1.16.5-2.3.7.jar                        |Mob Battle Mod                |mobbattle                     |1.16.5-2.3.7        |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 644d1c9b-9aa7-4750-a6cc-0c339c24723b
	Launched Version: 1.16.5
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	GPU Warnings: version: 2.1
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 9x null

**Comment by dshadowwolf** [comment]
Minecraft Forge only has official support on Windows, MacOS and Linux - with any other OS it is "Things might not and might not work" - according to this report, you're running OpenJDK on top of Android 11.

It might be that there is something that there can be things changed in the mod to fix this, but at this point I think its down to @skyjay1 to step in and take a look.

**Comment by pro14812345** [comment]
That's because I don't have a pc, so I got pojav launcher.
And also, my phone Android is 11, that means I have so much problems, android 11 just crashes some of my games, but my phone is a "A12pro" so it's not so much strong.

**Comment by skyjay1** [comment]
It looks like a block tag may be null (or empty). I'll add some checks to handle that, hopefully that will fix the crash.
Are you using any of the optional datapacks?

**Comment by pro14812345** [comment]
I'm not using datapacks, did I gotta use datapacks? 
i'm new to minecraft java.

**Comment by skyjay1** [comment]
No, the datapacks are optional. They add support for other mods, like Quark. I was just wondering because a malformed datapack could also contribute to this issue

**Comment by pro14812345** [comment]
And also, I can hit the bedrock golem, It goes red when I hit him and goes back to normal color but he not dies

**Comment by pro14812345** [comment]
I hope you guys can fix it because I saw so many youtubers played with this mod, I want too.

**Comment by pro14812345** [comment]
Oh my god I'm an idiot, I'm sorry, when you said "are you using datapacks?" I checked my folder and I saw that I Hava some datapacks, it works now, I'm so sorry, I was not thinking to that, I thought I emptied my datapack folder, 
That's because i'm new to minecraft java.

**Comment by pro14812345** [comment]
I'm so sorry for that☹.

**Comment by pro14812345** [comment]
I tested it and it's so cool but it have problem
guide book still crashes my game

**Comment by Drackus999** [comment]
Im also having this problem and im not quite sure why.. i think i have 1 data pack minus the additional one for the golems thats on the forge page for 1.16.5

**Comment by pro14812345** [comment]
Ok

**Comment by pro14812345** [comment]
Do I close the issue?

**Comment by pro14812345** [comment]
It's still a issue but idk
