### ISSUE TITLE
Inconsistent behavior, crashing, Exception ticking world

### ISSUE THREAD

**Issue by mhov** [MinecraftModDevelopment/Extra-Golems#95]
While there are similar issues out there, they were all seemingly not resolved, so thought I'd throw one more report into the mix with additional info. 

My setup: 
- brand new windows 10 install
- latest CurseForge v0.189.2.2
- latest version of Extra-Golems available on Curse Forge, v16.5.2
- Forge v36.2.22 (whatever CurseForge provided)
- Minecraft  v1.16.5
- no additional datapacks or mods and I'm noticing the following behavior 

The only non-standard thing might be using Adoptium as the JDK.

Mod Behavior:
- Only some blocks result in a golem forming (ex. Diamond, Gold, Leaves, Hay) while most others do nothing when placing the pumpkin
- Often, among the working recipes, the golem works once or twice, then not again unless I create a new world
- After 10-15 minutes I sometimes get a crash, and attempts to reopen that world results in an instance crash with the same errors in the logs.

I'm attaching the logs below, but one last question: Are there any plans to support MC 1.18.1?  I'm new to MC mods so not sure what the release cadence usually is for these projects.

Thanks for your time!

This is the log of starting the app via CurseForge to the first non-working golem recipe
```
[12:45:15] [main/INFO]: ModLauncher running: args [--username, myname, --version, forge-36.2.22, --gameDir, C:\Users\myname\curseforge\minecraft\Instances\Extra Golems, --assetsDir, C:\Users\myname\curseforge\minecraft\Install\assets, --assetIndex, 1.16, --uuid, 1e34a3381f394f779e5dc517c270cec6, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1024, --height, 768, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.22, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550]
[12:45:15] [main/INFO]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_51 by Oracle Corporation
[12:45:15] [main/WARN]: LEGACY JDK DETECTED, SECURED JAR HANDLING DISABLED
[12:45:15] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[12:45:15] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/myname/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[12:45:16] [main/INFO]: Launching target 'fmlclient' with arguments [--version, forge-36.2.22, --gameDir, C:\Users\myname\curseforge\minecraft\Instances\Extra Golems, --assetsDir, C:\Users\myname\curseforge\minecraft\Install\assets, --uuid, 1e34a3381f394f779e5dc517c270cec6, --username, myname, --assetIndex, 1.16, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1024, --height, 768]
[12:45:19] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[12:45:20] [main/INFO]: Setting user: myname
[12:45:20] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[12:45:21] [modloading-worker-2/INFO]: Forge mod loading, version 36.2.22, for MC 1.16.5 with MCP 20210115.111550
[12:45:21] [modloading-worker-2/INFO]: MinecraftForge v36.2.22 Initialized
[12:45:21] [modloading-worker-11/INFO]: golems:registerEventHandlers
[12:45:21] [modloading-worker-11/INFO]: golems:registerNetwork
[12:45:21] [main/INFO]: golems:registerBlocks
[12:45:21] [main/INFO]: golems:registerItems
[12:45:21] [main/INFO]: golems:registerEntities
[12:45:21] [main/INFO]: golems:registerEntityRenderers
[12:45:21] [main/INFO]: golems:registerContainers
[12:45:21] [main/INFO]: golems:registerContainerRenderers
[12:45:21] [main/INFO]: golems:registerEntityAttributes
[12:45:21] [main/INFO]: Narrator library for x64 successfully loaded
[12:45:22] [main/INFO]: Reloading ResourceManager: Default, Mod Resources
[12:45:22] [Forge Version Check/INFO]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[12:45:22] [Worker-Main-12/INFO]: golems:setupClient
[12:45:22] [Forge Version Check/INFO]: [forge] Found status: AHEAD Current: 36.2.22 Target: null
[12:45:24] [main/INFO]: OpenAL initialized.
[12:45:24] [main/INFO]: Sound engine started
[12:45:25] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[12:45:25] [main/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[12:45:25] [main/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[12:45:25] [main/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[12:45:25] [main/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[12:45:25] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[12:45:25] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[12:45:25] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[12:45:25] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[12:45:25] [main/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[12:46:30] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[12:46:30] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[12:46:30] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[12:46:30] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[12:46:30] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[12:46:30] [main/INFO]: Reloading ResourceManager: Default, forge-1.16.5-36.2.22-universal.jar, extragolems-16.5.2.jar
[12:46:30] [main/ERROR]: Couldn't load block tag forge:nether_bricks as it is missing following references: quark:charred_nether_bricks (from extragolems-16.5.2.jar)
[12:46:30] [main/INFO]: Loaded 7 recipes
[12:46:30] [main/INFO]: Loaded 927 advancements
[12:46:30] [main/INFO]: Parsing Reloadable JSON map of type com.mcmoddev.golems.golem_stats.GolemContainer
[12:46:30] [main/INFO]: Found 53 entries
[12:46:30] [main/INFO]: Parsing Reloadable JSON map of type com.mcmoddev.golems.golem_models.GolemRenderSettings
[12:46:30] [main/INFO]: Found 53 entries
[12:46:30] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[12:46:30] [Server thread/INFO]: Starting integrated minecraft server version 1.16.5
[12:46:30] [Server thread/INFO]: Generating keypair
[12:46:30] [Server thread/WARN]: Configuration file C:\Users\myname\curseforge\minecraft\Instances\Extra Golems\saves\New Golems 2\serverconfig\forge-server.toml is not correct. Correcting
[12:46:30] [Server thread/WARN]: Incorrect key server was corrected from null to its default, SimpleCommentedConfig:{}. 
[12:46:30] [Server thread/WARN]: Incorrect key server.removeErroringEntities was corrected from null to its default, false. 
[12:46:30] [Server thread/WARN]: Incorrect key server.removeErroringTileEntities was corrected from null to its default, false. 
[12:46:30] [Server thread/WARN]: Incorrect key server.fullBoundingBoxLadders was corrected from null to its default, false. 
[12:46:30] [Server thread/WARN]: Incorrect key server.zombieBaseSummonChance was corrected from null to its default, 0.1. 
[12:46:30] [Server thread/WARN]: Incorrect key server.zombieBabyChance was corrected from null to its default, 0.05. 
[12:46:30] [Server thread/WARN]: Incorrect key server.logCascadingWorldGeneration was corrected from null to its default, true. 
[12:46:30] [Server thread/WARN]: Incorrect key server.fixVanillaCascading was corrected from null to its default, false. 
[12:46:30] [Server thread/WARN]: Incorrect key server.dimensionUnloadQueueDelay was corrected from null to its default, 0. 
[12:46:30] [Server thread/WARN]: Incorrect key server.treatEmptyTagsAsAir was corrected from null to its default, false. 
[12:46:30] [Server thread/WARN]: Incorrect key server.fixAdvancementLoading was corrected from null to its default, true. 
[12:46:33] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[12:46:33] [main/INFO]: Preparing spawn area: 0%
[12:46:33] [main/INFO]: Preparing spawn area: 4%
[12:46:34] [main/INFO]: Preparing spawn area: 12%
[12:46:34] [main/INFO]: Preparing spawn area: 21%
[12:46:35] [main/INFO]: Preparing spawn area: 33%
[12:46:35] [main/INFO]: Preparing spawn area: 46%
[12:46:36] [main/INFO]: Preparing spawn area: 59%
[12:46:36] [main/INFO]: Preparing spawn area: 68%
[12:46:37] [main/INFO]: Preparing spawn area: 84%
[12:46:37] [main/INFO]: Preparing spawn area: 94%
[12:46:37] [main/INFO]: Time elapsed: 4529 ms
[12:46:37] [Server thread/INFO]: Changing view distance to 11, from 10
[12:46:38] [Netty Local Client IO #0/INFO]: Connected to a modded server.
[12:46:38] [Server thread/INFO]: Using new advancement loading for net.minecraft.advancements.PlayerAdvancements@d2bfe4b
[12:46:38] [Server thread/INFO]: myname[local:E:cf739018] logged in with entity id 222 at (221.5, 71.0, 137.5)
[12:46:38] [Server thread/INFO]: myname joined the game
[12:46:38] [Server thread/INFO]: Saving and pausing game...
[12:46:38] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New Golems 2]'/minecraft:overworld
[12:46:38] [main/INFO]: Loaded 0 advancements
[12:46:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New Golems 2]'/minecraft:the_nether
[12:46:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New Golems 2]'/minecraft:the_end
[12:47:06] [main/INFO]: Loaded 3 advancements
[12:47:11] [main/INFO]: Loaded 5 advancements
[12:47:15] [main/INFO]: Loaded 6 advancements
[12:47:22] [main/INFO]: Loaded 8 advancements
[12:47:28] [main/INFO]: Loaded 10 advancements
[12:47:32] [main/INFO]: Loaded 18 advancements
[12:48:45] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: null
	at com.mcmoddev.golems.golem_stats.GolemContainer.getAllBlocks(GolemContainer.java:359) ~[?:16.5.2]
	at com.mcmoddev.golems.golem_stats.GolemContainer.getAllBlocks(GolemContainer.java:270) ~[?:16.5.2]
	at com.mcmoddev.golems.golem_stats.GolemContainer.matches(GolemContainer.java:274) ~[?:16.5.2]
	at com.mcmoddev.golems.ExtraGolems.getGolemId(ExtraGolems.java:117) ~[?:16.5.2]
	at com.mcmoddev.golems.ExtraGolems.getGolem(ExtraGolems.java:136) ~[?:16.5.2]
	at com.mcmoddev.golems.block.GolemHeadBlock.trySpawnGolem(GolemHeadBlock.java:165) ~[?:16.5.2]
	at com.mcmoddev.golems.block.GolemHeadBlock.func_180633_a(GolemHeadBlock.java:50) ~[?:16.5.2]
	at net.minecraft.item.BlockItem.func_195942_a(BlockItem.java:66) ~[?:?]
	at net.minecraft.item.BlockItem.func_195939_a(BlockItem.java:39) ~[?:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:644) ~[?:?]
	at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:186) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:350) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:958) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$6225/284095759.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) [?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697) [?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) [?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$5340/1210663640.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```

This is the log of the crash, when trying to re-open a world it crashes instantly with the same output.

```
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 1/5/22 12:45 PM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at com.mcmoddev.golems.golem_stats.GolemContainer.getAllBlocks(GolemContainer.java:359) ~[?:16.5.2] {re:classloading}
	at com.mcmoddev.golems.golem_stats.GolemContainer.getAllBlocks(GolemContainer.java:270) ~[?:16.5.2] {re:classloading}
	at com.mcmoddev.golems.golem_stats.GolemContainer.matches(GolemContainer.java:274) ~[?:16.5.2] {re:classloading}
	at com.mcmoddev.golems.ExtraGolems.getGolemId(ExtraGolems.java:117) ~[?:16.5.2] {re:classloading}
	at com.mcmoddev.golems.ExtraGolems.getGolem(ExtraGolems.java:136) ~[?:16.5.2] {re:classloading}
	at com.mcmoddev.golems.block.GolemHeadBlock.trySpawnGolem(GolemHeadBlock.java:165) ~[?:16.5.2] {re:classloading}
	at com.mcmoddev.golems.block.GolemHeadBlock.func_196271_a(GolemHeadBlock.java:55) ~[?:16.5.2] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_196956_a(AbstractBlock.java:657) ~[?:?] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_241482_a_(AbstractBlock.java:597) ~[?:?] {re:classloading}
	at net.minecraft.world.World.markAndNotifyBlock(World.java:245) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.World.func_241211_a_(World.java:212) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.World.func_180501_a(World.java:176) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.World.func_175656_a(World.java:283) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.block.SpreadableSnowyDirtBlock.func_225542_b_(SpreadableSnowyDirtBlock.java:37) ~[?:?] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227034_b_(AbstractBlock.java:624) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217441_a(ServerWorld.java:508) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerChunkProvider.func_241099_a_(ServerChunkProvider.java:367) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider$$Lambda$5649/876498273.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(ServerChunkProvider.java:351) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:326) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$5340/618864390.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.mcmoddev.golems.golem_stats.GolemContainer.getAllBlocks(GolemContainer.java:359) ~[?:16.5.2] {re:classloading}
	at com.mcmoddev.golems.golem_stats.GolemContainer.getAllBlocks(GolemContainer.java:270) ~[?:16.5.2] {re:classloading}
	at com.mcmoddev.golems.golem_stats.GolemContainer.matches(GolemContainer.java:274) ~[?:16.5.2] {re:classloading}
	at com.mcmoddev.golems.ExtraGolems.getGolemId(ExtraGolems.java:117) ~[?:16.5.2] {re:classloading}
	at com.mcmoddev.golems.ExtraGolems.getGolem(ExtraGolems.java:136) ~[?:16.5.2] {re:classloading}
	at com.mcmoddev.golems.block.GolemHeadBlock.trySpawnGolem(GolemHeadBlock.java:165) ~[?:16.5.2] {re:classloading}
	at com.mcmoddev.golems.block.GolemHeadBlock.func_196271_a(GolemHeadBlock.java:55) ~[?:16.5.2] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_196956_a(AbstractBlock.java:657) ~[?:?] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_241482_a_(AbstractBlock.java:597) ~[?:?] {re:classloading}
	at net.minecraft.world.World.markAndNotifyBlock(World.java:245) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.World.func_241211_a_(World.java:212) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.World.func_180501_a(World.java:176) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.World.func_175656_a(World.java:283) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.block.SpreadableSnowyDirtBlock.func_225542_b_(SpreadableSnowyDirtBlock.java:37) ~[?:?] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227034_b_(AbstractBlock.java:624) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217441_a(ServerWorld.java:508) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerChunkProvider.func_241099_a_(ServerChunkProvider.java:367) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider$$Lambda$5649/876498273.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(ServerChunkProvider.java:351) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:326) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?] {re:classloading}
-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['myname'/185, l='ServerLevel[New Golems]', x=137.46, y=75.49, z=-249.04]]
	Chunk stats: ServerChunkCache: 2301
	Level dimension: minecraft:overworld
	Level spawn location: World: (112,72,-240), Chunk: (at 0,4,0 in 7,-15; contains blocks 112,0,-240 to 127,255,-225), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 38184 game time, 38184 day time
	Level name: New Golems
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 110153 (now: false), thunder time: 124310 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$5340/618864390.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1179535008 bytes (1124 MB) / 1900019712 bytes (1812 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 16
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.22.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.22.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.22.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.22.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.22.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.22
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.22-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.22-universal.jar                |Forge                         |forge                         |36.2.22             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		extragolems-16.5.2.jar                            |Extra Golems                  |golems                        |16.5.2              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: d2e8ca93-c143-406b-880c-0ec52b1ff265
	Player Count: 1 / 8; [ServerPlayerEntity['myname'/185, l='ServerLevel[New Golems]', x=137.46, y=75.49, z=-249.04]]
	Data Packs: vanilla, mod:forge, mod:golems
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
```

**Comment by skyjay1** [comment]
Yep, same problem as #89 and #93 . It's a very small fix, just a NPE check on one line, but I haven't had time due to other obligations. My apologies.
